#!/bin/bash
if [ "$1" == "" ]; then echo "* usage: $0 [latest|stable]";false;exit;fi
BRANCH="$1"
wget --content-disposition "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/$BRANCH-virtio/virtio-win.iso"