#!/bin/bash
# source: https://wiki.archlinux.org/index.php/Port_knocking#Port_knocking_script
HOST=$1
shift
for ARG in "$@"
do
    nmap -Pn --host_timeout 100 --max-retries 0 -p $ARG $HOST >/dev/null
done
