#!/bin/bash
APP_TITLE="MAC resolver 0.41 by lurid@dmnc.net, 2012"
BASEDIR="${0%/*}"
DATADIR="$BASEDIR/mac_data"			# customizable
DATABASE="$DATADIR/ieee-macs"			# customizable
TMPFILE="/tmp/ieee-macs"
URL_IEEE="http://standards-oui.ieee.org/oui.txt"
URL_WIRESHARK="https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf"
ARPTABLE="/proc/net/arp"
DEBUG=false
MINIMAL=false

function print_license {
    echo -e 'Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.'
    quit
}

function quit {
    if $DEBUG; then echo "* cleanup and quit...";fi
    if ! $MINIMAL; then echo; fi;
    if [ "$TMPFILE" != "" ]; then if [ -f $TMPFILE ]; then rm $TMPFILE; fi; fi
    if ! $1; then false; fi
    exit
}

function intro {
    echo
    echo -e "\e[1;37m$APP_TITLE\e[0m"
    echo
}


function check_database {
    if [ ! -f $DATABASE ]; then echo " * database not found, use --update command";quit false;fi
}


function check_datadir {
    if [ ! -d $DATADIR ]; then									# create datadir if not exist
	echo -ne " * creating datadir... ";mkdir -p $DATADIR&&echo "[OK]"
	if [ $? -ne 0 ]; then echo " * can't create directory $DATADIR";quit false;fi	# check if can create dir
    fi
    touch $DATABASE
    if [ ! -w $DATABASE ]; then echo " * can't write database file $DATABASE";quit false;fi		# check if database is writable
}


function update_ieee {
    check_datadir
    echo -ne " * updating MAC db (the obsolete source)... "
    wget -q -O $TMPFILE "$URL_IEEE"&&echo "[OK]"||echo "[ERROR!]"
    echo -n " * parsing... "
    grep "(hex)" $TMPFILE|sed 's/-/:/1;s/-/:/1;s/   (hex)\t//'>$DATABASE&&echo "[OK]"||echo "[ERROR!]"
    rm $TMPFILE
    quit
}

function update_wireshark {
    check_datadir
    echo -ne " * updating MAC db... "
    wget -q -O $TMPFILE "$URL_WIRESHARK"&&echo "[OK]"||echo "[ERROR!]"
    echo -n " * parsing... "
    sed -E 's/#.*$//;/^$/d;s/:00:00\/28//;s/:00\/36//;s/\t.{1,8}\t/\t/' $TMPFILE>$DATABASE&&echo "[OK]"||echo "[ERROR!]"
    rm $TMPFILE
    quit
}

function print_changelog {
    echo -e '
0.4 [2019-06-04]
 - added Wireshark database
 - rework of the db and engine
 - input is converted and validated
 - fixed datadir wtf
 - help page changes

0,31 [2014-12-22]
 - datadir hotfix (wtf)
 
0.3 [2012-10-29]
 - minimal output
 - database/datadir checks

0.2 [2012-03-30]
 - automated ARP table resolver

0.1 [2012-03-12]
 - 1st version
'
    quit
}


function help {
    echo -e "\tUsage:"
    echo -e "\t$0 MAC [--option]"
    echo -e "\t$0 --command"
    echo
    echo -e "\tMAC\t\txx:xx:xx:xx:xx:xx (at least first 3 segments), allowed delimiters are ':' or '-' or none"
    echo -e "\t--minimal\tMinimal output, only vendor/company information (not applicable with --arptable)"
    echo
    echo -e "\tCommands (standalone, higher priority):"
    echo -e "\t--arptable\tResolve all macs in arptable"
    echo -e "\t--license"
    echo -e "\t--changelog"
    echo -e "\t--update\tUpdate database (source: Wireshark)"
    echo -e "\e[0;90m\t--update-ieee\tUpdate database (source: IEEE) [obsolete]\e[m\n"
    echo
    echo
    quit
}


function commands {
    for par in "$@"; do
        CMD=`echo "$par"|awk -F "--" '{print $2}'|awk -F "=" '{print $1}'`		#get command or options
#        VAL=`echo "$par"|awk -F "--" '{print $2}'|awk -F "=" '{print $2}'`		#get value, not used now
	case $CMD in
	    licence|license)
		ACTION="print_license"
		;;
	    changelog)
		ACTION="print_changelog"
		;;
	    update-ieee)
		ACTION="update_ieee"
		;;
	    update)
		ACTION="update_wireshark"
		;;
	    arptable)
		ACTION="check_arptable"
		;;
	    minimal)
		MINIMAL=true
		;;
	esac
	if $DEBUG; then echo "* command $CMD value $VAL";fi
    done
}


function normalize_mac {
    read RAW
    echo $RAW|tr '[[:lower:]]' '[[:upper:]]'|sed 's/[:-]//g;s/[0-9A-F]\{2\}/&\:/g;s/\:$//'
}

function make_pattern {
    # strip first ($2) characters of the parameter ($1)
    PATTERN=${1:0:$2}
}


function check_arptable {
    cat $ARPTABLE|grep -v '00:00:00:00:00:00'|tail -n +2|awk '{print $1"\t"$4}'|sort|uniq>$TMPFILE
    while read LINE; do
	IP=$(cut -f1 <<< ${LINE})
	MAC=$(cut -f2 <<< ${LINE}|normalize_mac)
	check_mac $MAC $IP dontquit
    done < $TMPFILE
    quit
}

function check_mac {
    MAC="$1"
    IP="$2"
    check_database
    for PATTERN_LEN in 8 11 14; do					# 8 = classic 12:45:78 record
	make_pattern $MAC $PATTERN_LEN
	RESULT=`grep "$PATTERN" $DATABASE|awk -F "\t" '{print $2}'`	# most important line in this script
	if [ $(wc -l <<< "${RESULT}") -lt 2 ]; then break; fi		# finish with just 0/1 results
	if [ ${#MAC} -lt $PATTERN_LEN ]; then echo " * multiple results found (MAC pattern is too short)"; quit false; fi
    done

    if [ "$IP" != "" ]; then echo -en " * $MAC - $IP\t";fi
    if ! $MINIMAL; then echo -ne "$PATTERN - ";fi
    echo $RESULT
    if [ "$3" != "dontquit" ]; then quit;fi
}

########################## MAIN ####################################

commands $@						# get action
if ! $MINIMAL; then intro;fi
$ACTION							# call action

if [ "$1" != "" ]; then
    MAC=$(echo $1|normalize_mac)
    INVALID=$(sed -E 's/[0-9A-F:]//g' <<< ${MAC})
    if (( ${#INVALID} > 0 )); then echo " * $MAC is not valid MAC!"; quit false; fi
    if (( ${#MAC} >=8 && ${#MAC} <= 17 )); then check_mac $MAC; else echo " * MAC pattern is too short or long!"; quit false; fi
fi

help							# or if passed up to here, show help
quit
